config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  resources :departments do
    resources :pets
  end

  resources :pets do
    resources :comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  before_save :check_author
  belongs_to :pet

  def check_author
    if self.author.blank?
      self.author = 'anon'
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :pets
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :department
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_pet

  def new
    @comment = Comment.new
  end

  def create
    @comment = @pet.comments.new(comment_params)
    if @comment.save
      redirect_to department_pet_path(@pet.department_id, @pet)
    else
      render :new
    end
  end

  private
    def set_pet
      @pet = Pet.find(params[:pet_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author)
    end
end

app/controllers/departments_controller.rb
require 'pry'
class DepartmentsController < ApplicationController

  def index
    @departments = Department.all
  end

  def show
    @department = Department.find(params[:id])
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(params.require(:department).permit(:name))

    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])

    if @department.update(params.require(:department).permit(:name))
      redirect_to departments_path
    else
      render :edit
    end
  end

  def destroy
    Department.find(params[:id]).destroy
    redirect_to departments_path
  end

  # private

  # def departments_params
  #   departments.require(:department).permit(:name)
  # end



end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_department
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = @department.pets
  end

  def show
  end

  def new
    @pet = @department.pets.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @pet = @department.pets.new(pet_params)
    if @pet.update(pet_params)
      redirect_to [@department, @pet]
    else
      render :new
    end
  end

  def update
    if @pet.update(pet_params)
      redirect_to [@department, @pet]
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to department_pets_path(@department)
  end

    private
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_pet
      @pet = Pet.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :species, :color, :age, :favorite_thing, :gender)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<div class="box">
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %></strong></p>
</hr>
</div>

app/views/comments/new.html.erb
<h1>Add A Comment</h1>
<%= form_for [@pet, @comment] do |p| %>
  <%= p.label :body %>
  <%= p.text_area :body, required: true %>
  <br />
  <%= p.label :author %>
  <%= p.text_field :author, placeholder: 'Leave Blank To Remain Anonymous' %>
  <br />
  <%= p.submit %>
<% end %>

app/views/departments/edit.html.erb
<h1>Edit Department</h1>
<%= form_for @department do |d| %>
  <%= d.label :name %>
  <%= d.text_field :name %>
  
  <%= d.submit %>
<% end %>

app/views/departments/index.html.erb
<div class="header">

<h1> Categories  </h1> 

</div>


<% @departments.each do |department| %>
  <div class="box">
  <h2>
  <%= department.name %>
  </h2>
  </div>
  <div class="link">
  <%= link_to 'Show Pets', department_path(department) %>
  <%= link_to 'New Category', new_department_path %>
  <%= link_to 'Edit Category', edit_department_path(department) %>
  <%= link_to 'Destroy Category', department, method: :delete %>
  </div>
<% end %>

app/views/departments/new.html.erb
<h1>New Department</h1>
<%= form_for @department do |d| %>
  <%= d.label :name %>
  <%= d.text_field :name %>

  <%= d.submit %>
<% end %>

app/views/departments/show.html.erb
<div class="box">
<h1><%= @department.name %></h1>
<%= link_to 'View Pets', department_pets_path(@department) %>
<br />
<%= link_to 'Back', departments_path %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
<%= link_to 'Home', root_path %>
<%= link_to 'Categories', departments_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "styles.css" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<h1><%= @pet.id ? 'Edit Pet' : 'Create Pet' %></h1>
<hr />
<%= form_for [@department, @pet] do |p| %>
  <%= p.label :name %>
  <%= p.text_field :name, required: true, autofocus: true %>
  <br />
  <%= p.label :age %>
  <%= p.text_area :age, required: true %>
  <br />
  <%= p.label :gender %>
  <%= p.text_field :gender, required: true %>
  <br />
  <%= p.label :species %>
  <%= p.text_field :species, required: true %>
  <br />
  <%= p.label :color %>
  <%= p.text_field :color, required: true %>
  <br />
  <%= p.label :favorite_thing %>
  <%= p.text_field :favorite_thing, required: true %>
  <br />
  <%= p.submit %>
<% end %>

app/views/pets/edit.html.erb
<h1>Pets#edit</h1>
<p>Find me in app/views/pets/edit.html.erb</p>

app/views/pets/index.html.erb
<div class="header">

<h1>Click A Pet For More Details</h1>

<div>


<div class="box">
<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, [@department, pet] %></li>
  <% end %>
  <%= link_to 'Create a new pet', new_department_pet_path(@department) %>
</ul>
</div>

app/views/pets/new.html.erb
<h1>Pets#new</h1>
<p>Find me in app/views/pets/new.html.erb</p>

app/views/pets/show.html.erb
<div class ="header">
<h1><%= @department.name %> - <%= @pet.name %></h1>
</div>
<div class="box">
<p> Name: <%= @pet.name %></p>
<p> Age: <%= @pet.age %></p>
<p> Gender: <%= @pet.gender %></p>
<p> Species: <%= @pet.species %></p>
<p> Color: <%= @pet.color %></p>
<p> Favorite Thing: <%= @pet.favorite_thing %></p>
</div>

<h2>Comments</h2>

<% @pet.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
<% end %>

<%= link_to 'Add Comment', new_pet_comment_path(@pet) %>
<%= link_to 'Edit Pet', edit_department_pet_path([@department, @pet]) %>
<%= link_to 'Delete Pet', [@department, @pet], method: :delete %>
<%= link_to 'Back To Pets', department_pets_path(@department) %>

app/views/static_pages/home.html.erb
<div class="box">
<h1>Pet Department Store</h1>
<h3>Welcome!</h3>
</div>